version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=gobank-postgres-user
      - POSTGRES_PASSWORD=gobank-postgres-password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local